### ISSUE TITLE
拖拽相关

### ISSUE THREAD

**Issue by FreezingRiver** [Lzzzzzq/vue-mobile-page-creater#2]
请问有尝试过左边的组件直接拖拽到中间的iframe中吗？如有踩坑，请赐教

**Comment by Lzzzzzq** [comment]
> 请问有尝试过左边的组件直接拖拽到中间的iframe中吗？如有踩坑，请赐教

拖拽的话，我理解是没法带入到 iframe 中的，可以选择预览区域不使用 iframe。
当初用 iframe 是考虑移动端会有 fixed 布局的元素存在，其实给预览区域的容器加一个 transform 的话，就可以解决了。
fixed 的定位会相对于 body 或 带有 transform 属性的元素。

**Comment by FreezingRiver** [comment]
我搞了一下，确实无法直接实现。有一个比较tricky的解决办法，就是在处罚拖动事件的时候，在iframe上临时创建一个mask，并且复制iframe内容，伪装成拖入到iframe的样子

**Comment by Lzzzzzq** [comment]
> 我搞了一下，确实无法直接实现。有一个比较tricky的解决办法，就是在处罚拖动事件的时候，在iframe上临时创建一个mask，并且复制iframe内容，伪装成拖入到iframe的样子

挺有趣的想法，不过这样只是解决了一部分问题，拖拽到 iframe 以后不能直接做排序操作了

**Comment by Lzzzzzq** [comment]
> 我搞了一下，确实无法直接实现。有一个比较tricky的解决办法，就是在处罚拖动事件的时候，在iframe上临时创建一个mask，并且复制iframe内容，伪装成拖入到iframe的样子

你的意思是完全复制 iframe 里的内容吗？

**Comment by FreezingRiver** [comment]
是的
```
<iframe></iframe> // iframe
<div class='mask'>
// 复制iframe内容，拖拽时出现并且盖住iframe
// 拖拽完成后立刻渲染iframe，伪装成是在iframe上拖拽的样子
</div>
```

**Comment by Lzzzzzq** [comment]
> 是的
> 
> ```
> <iframe></iframe> // iframe
> <div class='mask'>
> // 复制iframe内容，拖拽时出现并且盖住iframe
> // 拖拽完成后立刻渲染iframe，伪装成是在iframe上拖拽的样子
> </div>
> ```

感觉方案是可行的，不过你选择用 iframe 的原因是什么呢

**Comment by FreezingRiver** [comment]
> 感觉方案是可行的，不过你选择用 iframe 的原因是什么呢
为了尽可能仿真以及代码复用

**Comment by FreezingRiver** [comment]
> 感觉方案是可行的，不过你选择用 iframe 的原因是什么呢

为了尽可能仿真和代码复用
